language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q pylibmc==1.3.0
  - python setup.py -q install

script:
  - python manage.py test tests

services:
  - memcached