language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

env:
    - DJANGO_VERSION=1.6
    - DJANGO_VERSION=1.7
    - DJANGO_VERSION=1.8

install:
    - pip install -q Django==$DJANGO_VERSION
    - pip install -q pylibmc
    - python setup.py -q install

matrix:
    exclude:
    - python: 3.4
        env: DJANGO_VERSION=1.6
    - python: 3.5
        env: DJANGO_VERSION=1.6
        env: DJANGO_VERSION=1.7

script:
    - python manage.py test tests

services:
    - memcached